config/routes.rb
Rails.application.routes.draw do
  resources :places
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 # sign up page with from:
 # get 'users/new' => 'users#new', as: :new_user

 # create (post) action for when sign up form is submitted :
 # post 'users' => 'users#create'

 # login in page with form:
 get '/login' => 'sessions#new'

 # create (post) action for when log in form is submitted:
 post '/login' => 'sessions#create'
 delete '/logout' => 'sessions#destroy'
 root 'beranda#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord


mount_uploader :avatar, AvatarUploader

end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	#verify that email field is not blank and that doesn't already exist in the db (prevents duplicates):
	validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	protect_from_forgery with: :exception

	helper_method :current_user

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def authorize 
		redirect_to login_path, alert: 'Musti maso dolo bu!' if current_user.nil?
	end
end

app/controllers/beranda_controller.rb
class BerandaController < ApplicationController
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  # before_action :authorize, except: [:show, :index]
  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:latitude, :longitude, :nama_wisata, :alamat, :tahun_berdiri, :luas, :fasilitas, :waktu_operasional, :tarif_masuk, :avatar)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new 
		# No need for anything in here, we are just going to render our
		# new.html.erb AKA the login page
	end

	def create 
		user = User.find_by(email: params[:login][:email].downcase)	

		if user && user.authenticate(params[:login][:password])
			session[:user_id] = user.id.to_s
			redirect_to root_path, notice: 'Ale su maso!'
		else
			flash.now.alert = "jang isi katasandi sabarang. jang maeng-maeng"
			render :new
		end
	end
	def destroy 
		session.delete(:user_id)
		redirect_to login_path, notice: "Ale su kaluar!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new 
		@user = User.new
	end

	def create 
		@user = User.new(user_params)
		
		# store all emails in lowercase to avoid duplicates and cas sensitive login errors:
		@user.email.downcase!

		if @user.save
			#If user saves in the db successfully:
			flash[:notice] = "Account created successfully!"
			redirect_to root_path
		else
			# If user fails model validation - probably a bad password or duplicate email:
			flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password"
			render :new
		end
	end

private
	def user_params 
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beranda_helper.rb
module BerandaHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/beranda/index.html.erb
<center>
<h1>SISTEM INFORMASI GEOGRAFIS</h1>
<h3 class="beranda-h2">PARIWISATA DI P.AMBON</h3>
<%= link_to 'REKOMENDASI WISATA', places_path, :class => "btn btn-lg btn-primary beranda-font"%>
</center>

app/views/layouts/_header.html.erb
<div style="background-color: #de493c">
		<h1>tes</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SigWisataAmbon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%=javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+Rails.application.credentials.google_maps_api_key %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head_tags) %>
  </head>

  <body>

    <% if notice %>
        <%= notice %>
    <% end %>

    <% if alert %>
        <%= alert %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nama_wisata %>
    <%= form.text_field :nama_wisata %>
  </div>
  <div class="field">
    <%= form.label :alamat %>
    <%= form.text_field :alamat %>
  </div>
  <div class="field">
    <%= form.label :tahun_berdiri %>
    <%= form.text_field :tahun_berdiri%>
  </div>
  <div class="field">
    <%= form.label :luas%>
    <%= form.text_field :luas%>
  </div>
  <div class="field">
    <%= form.label :fasilitas%>
    <%= form.text_area :fasilitas%>
  </div>
  <div class="field">
    <%= form.label :waktu_operasional%>
    <%= form.text_area :waktu_operasional%>
  </div>
  <div class="field">
    <%= form.label :tarif_masuk%>
    <%= form.text_area :tarif_masuk%>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <legend>Polygon</legend>
    <%= form.file_field :avatar%>
    
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Wisata di P.Ambon</h1>

<table>
  <thead>
    <tr>
      <th>Alamat</th>
      <th>Tahun Berdiri</th>
      <th>Luas</th>
      <th>Fasilitas</th>
      <th>Waktu Operasional</th>
      <th>Tarif Masuk</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Polygon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  
    <% @places.each do |place| %>
      <tr>
        <td><%= place.nama_wisata %></td>
        <td><%= place.alamat %></td>
        <td><%= place.tahun_berdiri%></td>
        <td><%= place.luas%><sub>2</sub></td>
        <td><%= place.fasilitas%></td>
        <td><%= place.waktu_operasional%></td>
        <td><%= place.tarif_masuk%></td>
        <td><%= place.latitude %></td>
        <td><%= place.longitude %></td>
        <td><%= place.avatar%></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'Tambah wisata', new_place_path %>
      bukang 

<%=  link_to 'Beranda', root_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
 <style>
      #map {
    width: 600px;
    height: 400px;
}
    </style>

<% provide :head_tags do %>
	<meta name='turbolinks-visit-control' content='reload'>
    <script>
    document.addEventListener("DOMContentLoaded", function(){
        initMap(<%=@place.latitude%>, <%=@place.longitude%>)
    });
    </script>
<% end %>

<p id="notice"><%= notice %></p>
<p>
  <strong>Nama Wisata:</strong>
  <%= @place.nama_wisata %>
</p>

<p>
  <strong>Alamat:</strong>
  <%= @place.alamat %>
</p>

<p>
  <strong>Tahun Berdiri:</strong>
  <%= @place.tahun_berdiri%>
</p>

<p>
  <strong>Luas:</strong>
  <%= @place.luas%><sub>2</sub>
</p>

<p>
  <strong>Fasilitas:</strong>
  <%= @place.fasilitas%>
</p>

<p>
  <strong>Waktu Operasional:</strong>
  <%= @place.waktu_operasional%>
</p>

<p>
  <strong>Tarif Masuk:</strong>
  <%= @place.tarif_masuk%>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<p>
  <strong>Polygon:</strong>
  <% unless @place.avatar_url.nil? %><%= image_tag @place.avatar_url(:display)%><br />
  <% end %>
</p>

<p>
	<h2>Map Dinamis</h2><br>
	<div id="map"></div>

  <script>
      function initMap(lat, lng) {
    var myCoords = new google.maps.LatLng(lat, lng);
    var mapOptions = {
    center: myCoords,
    zoom: 14
    };
    var map = new google.maps.Map(document.getElementById('map'), mapOptions);

    var marker = new google.maps.Marker({
    	position: myCoords,
    	map: map
    });
}
    </script>
</p>



<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>